services:
  rust-devenv:
    build:
      context: .
    tty: true
    privileged: true
    volumes:
       - .:/project
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/project
    devices: 
      - /dev/snd
