services:
  rust-devenv:
    build:
      context: .
    tty: true
    privileged: true
    volumes:
       - .:/project
       - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - WINIT_UNIX_BACKEND=x11
    devices: 
      - /dev/dxg
    network_mode: "host"
    user: "${UID}:${GID}"
