services:
  rust-devenv:
    build:
      context: .
    tty: true
    privileged: true
    volumes:
       - .:/project
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/project
      - WINIT_UNIX_BACKEND=x11
    devices: 
      - /dev/snd
    network_mode: "host"
