services:
  karta-rust-devenv:
    build:
      context: .
    container_name: karta-rust-devenv
    environment:
      - DISPLAY=${DISPLAY}
    devices: 
# Next line is for sound, but it does not work in Windows/WSL
#      - "/dev/snd:/dev/snd"
      - "/dev/dri:/dev/dri"
    tty: true
#    privileged: true
    volumes:
       - .:/project
       - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash
    deploy: 
      resources: 
        reservations: 
          devices: 
            - driver: nvidia
              count: 1
              capabilities: [gpu]
