[package]
name = "fs_graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
agdb = "0.8.0"
directories = "5.0.1"

[dev-dependencies]
git2 = "0.19.0"
ron = "0.8.1"
serde = {version = "1.0.210", features = ["derive"]}
